# Generated by Django 4.2.3 on 2023-10-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('moderation', 'На модерации'), ('approved', 'Одобрена'), ('deleted', 'На удалении')], default='approved', max_length=20),
        ),
    ]
